# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/


# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: PCIbex Documentation
description: >- # this means to ignore newlines until "baseurl:"
  PCIbex documentation
baseurl: "/pcibex" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
excerpt_separator: <!--more-->


# Build settings
remote_theme: pmarsceill/just-the-docs
# theme: just-the-docs
logo: "/assets/images/pcibex-logo.png"
# Aux links for the upper right navigation
aux_links:
  "Go to the PCIbex Farm":
    - "https://expt.pcibex.net/"
# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true
plugins:
  - jekyll-feed

# Disable Rouge syntax highlighter
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true

# Footer: appears at the bottom of every page's main content
footer_content: "<b>Contact us</b>&#58; <a href=\"mailto&#58; admin@pcibex.net\">admin@pcibex.net</a>"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html


# Collections
collections_dir: reference
collections:
  core-concepts:
    output: true
    permalink: /docs/:collection/:name/
  elements:
    output: true
    permalink: /docs/:collection/:name/
    order:
      - standard.md
  global-commands:
    output: true
    permalink: /docs/:collection/:name/
  special-commands:
    output: true
    permalink: /docs/:collection/:name/
  how-to-guides:
    output: true
    permalink: /docs/:collection/:name/
  audio:
    output: true
    permalink: /docs/:collection/:name/
  button:
    output: true
    permalink: /docs/:collection/:name/
  canvas:
    output: true
    permalink: /docs/:collection/:name/
  controller:
    output: true
    permalink: /docs/:collection/:name/
  dropdown:
    output: true
    permalink: /docs/:collection/:name/
  eyetracker:
    output: true
    permalink: /docs/:collection/:name/
  function:
    output: true
    permalink: /docs/:collection/:name/
  html:
    output: true
    permalink: /docs/:collection/:name/
  image:
    output: true
    permalink: /docs/:collection/:name/
  key:
    output: true
    permalink: /docs/:collection/:name/
  mediarecorder:
    output: true
    permalink: /docs/:collection/:name/
  mousetracker:
    output: true
    permalink: /docs/:collection/:name/
  scale:
    output: true
    permalink: /docs/:collection/:name/
  selector:
    output: true
    permalink: /docs/:collection/:name/
  standard:
    output: true
    permalink: /docs/:collection/:name/
  text:
    output: true
    permalink: /docs/:collection/:name/
  textinput:
    output: true
    permalink: /docs/:collection/:name/
  timer:
    output: true
    permalink: /docs/:collection/:name/
  tooltip:
    output: true
    permalink: /docs/:collection/:name/
  var:
    output: true
    permalink: /docs/:collection/:name/
  video:
    output: true
    permalink: /docs/:collection/:name/           
  youtube:
    output: true
    permalink: /docs/:collection/:name/

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".

# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
