# Site settings
title: PCIbex Documentation
description: >- # this means to ignore newlines until "baseurl:"
  PCIbex documentation
baseurl: "/pcibex"
url: "" 
excerpt_separator: <!--more-->

# Build settings
# remote_theme: pmarsceill/just-the-docs
theme: just-the-docs
logo: "/assets/images/pcibex-logo.png"
# Aux links for the upper right navigation
aux_links:
  "Go to the PCIbex Farm":
    - "https://expt.pcibex.net/"
# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true
plugins:
  - jekyll-feed
  - jekyll-paginate

# Announcements
paginate: 10
paginate_path: "/announcements/page/:num/"

# Disable Rouge syntax highlighter
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true

# Footer: appears at the bottom of every page's main content
footer_content: "<b>Contact us</b>&#58; <a href=\"mailto&#58; admin@pcibex.net\">admin@pcibex.net</a>"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Collections
collections_dir: reference
collections:
  author:
    output: true
    permalink: /:collection/:name/
  deprecated:
    output: true
    permalink: /:collection/:name/
  elements:
    output: true
    permalink: /:collection/:name/
  global-commands:
    output: true
    permalink: /commands/:collection/:name/
  how-to-guides:
    output: true
    permalink: /docs/:collection/:name/
  posts:
    output: true
    permalink: /announcements/:name/
  special-commands:
    output: true
    permalink: /commands/:collection/:name/
  standard-element-commands:
    output: true
    permalink: /commands/:collection/:name/
  audio:
    output: true
    permalink: /elements/:collection/:name/
  button:
    output: true
    permalink: /elements/:collection/:name/
  canvas:
    output: true
    permalink: /elements/:collection/:name/
  controller:
    output: true
    permalink: /elements/:collection/:name/
  dropdown:
    output: true
    permalink: /elements/:collection/:name/
  eyetracker:
    output: true
    permalink: /elements/:collection/:name/
  function:
    output: true
    permalink: /elements/:collection/:name/
  html:
    output: true
    permalink: /elements/:collection/:name/
  image:
    output: true
    permalink: /elements/:collection/:name/
  key:
    output: true
    permalink: /elements/:collection/:name/
  mediarecorder:
    output: true
    permalink: /elements/:collection/:name/
  mousetracker:
    output: true
    permalink: /elements/:collection/:name/
  scale:
    output: true
    permalink: /elements/:collection/:name/
  selector:
    output: true
    permalink: /elements/:collection/:name/
  text:
    output: true
    permalink: /elements/:collection/:name/
  textinput:
    output: true
    permalink: /elements/:collection/:name/
  timer:
    output: true
    permalink: /elements/:collection/:name/
  tooltip:
    output: true
    permalink: /elements/:collection/:name/
  var:
    output: true
    permalink: /elements/:collection/:name/
  video:
    output: true
    permalink: /elements/:collection/:name/           
  youtube:
    output: true
    permalink: /elements/:collection/:name/

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
